spring:
  application:
    name: kotlin-backend

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB


### Application Properties
bucket:
  endpoint: "http://localhost:9000"
  access-key: "minio_admin_user"
  secret-key: "supersecretpassword123"
  name: "songs"
